/**
 * Service worker: cache-first for everything the game is made of.
 *
 * The game has no backend and no runtime fetches of its own, so caching is the whole story —
 * once the shell is in, the game runs in flight mode exactly as it does online. Cache-first is
 * the right policy for that: the cached copy is not a stale approximation of something on a
 * server, it *is* the version that was installed, and a new one only arrives with a new worker.
 *
 * The PRECACHE list below is generated by `npm run sw` and checked in CI, so it cannot quietly
 * fall behind the source. Do not edit it by hand.
 */

/**
 * The released version. A new value means a new cache and a fresh copy of every file; the page
 * notices the new worker and offers a reload rather than swapping anything mid-race.
 */
const VERSION = 'v1.1.0';
const CACHE = `pferderennen-${VERSION}`;

/* --- precache:start --- */
const PRECACHE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './src/audio/audio.js',
  './src/audio/sfx.js',
  './src/audio/voices.js',
  './src/config.js',
  './src/data/avatars.js',
  './src/data/commentary.js',
  './src/data/events.js',
  './src/data/horses.js',
  './src/engine/effectSlots.js',
  './src/engine/effects.js',
  './src/engine/eventScheduler.js',
  './src/engine/payout.js',
  './src/engine/race.js',
  './src/engine/rng.js',
  './src/engine/speedModel.js',
  './src/main.js',
  './src/render/attract.js',
  './src/render/camera.js',
  './src/render/ceremony.js',
  './src/render/crowdFlashes.js',
  './src/render/eventEmitters.js',
  './src/render/eventProps.js',
  './src/render/eventVisuals.js',
  './src/render/field.js',
  './src/render/finishTape.js',
  './src/render/horse.js',
  './src/render/horseAnimations.js',
  './src/render/horsePortrait.js',
  './src/render/horseRear.js',
  './src/render/horseTack.js',
  './src/render/hud.js',
  './src/render/jockeyStanding.js',
  './src/render/loop.js',
  './src/render/palette.js',
  './src/render/particles.js',
  './src/render/quality.js',
  './src/render/shapes.js',
  './src/render/sprites.js',
  './src/render/starter.js',
  './src/render/track.js',
  './src/render/trackLandscape.js',
  './src/render/trackPortrait.js',
  './src/render/trackTheme.js',
  './src/state/persistence.js',
  './src/state/reducers.js',
  './src/state/store.js',
  './src/styles/base.css',
  './src/styles/components.css',
  './src/styles/race.css',
  './src/styles/screens.css',
  './src/styles/tokens.css',
  './src/ui/bettingSummary.js',
  './src/ui/components/button.js',
  './src/ui/components/countdown.js',
  './src/ui/components/history.js',
  './src/ui/components/layout.js',
  './src/ui/components/modal.js',
  './src/ui/components/stepper.js',
  './src/ui/components/toast.js',
  './src/ui/debug.js',
  './src/ui/dom.js',
  './src/ui/raceAudio.js',
  './src/ui/raceCeremony.js',
  './src/ui/raceCommentary.js',
  './src/ui/raceDebug.js',
  './src/ui/raceNarration.js',
  './src/ui/racePhotoFinish.js',
  './src/ui/raceResult.js',
  './src/ui/router.js',
  './src/ui/screens/betting.js',
  './src/ui/screens/players.js',
  './src/ui/screens/race.js',
  './src/ui/screens/results.js',
  './src/ui/screens/rules.js',
  './src/ui/screens/settings.js',
  './src/ui/screens/start.js',
  './src/ui/screens/stats.js',
  './src/ui/strings.js',
  './assets/icons/apple-touch-icon.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-512.png',
];
/* --- precache:end --- */

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // One miss must not fail the whole install, so each file is added on its own.
      await Promise.all(
        PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => {})),
      );
      // The new worker is ready as soon as it is installed; the page decides when to use it.
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached) return cached;

      try {
        const response = await fetch(request);
        // Only own, successful, basic responses are worth keeping.
        if (response.ok && response.type === 'basic') {
          const cache = await caches.open(CACHE);
          cache.put(request, response.clone());
        }
        return response;
      } catch {
        // Offline and not in the cache. A navigation still has somewhere to go: the shell.
        if (request.mode === 'navigate') {
          const shell = await caches.match('./index.html');
          if (shell) return shell;
        }
        return new Response('', { status: 504, statusText: 'Offline' });
      }
    })(),
  );
});
